export const WORD_BANK = {
    Korea: {
      animals: [
        "Korean Tiger",
        "Korean Water Deer",
        "Jeju Pony",
        "Amur Leopard",
        "Asiatic Black Bear",
        "Korean Magpie",
        "Red-crowned Crane",
        "Korean Goral",
        "Ussuri Boar",
        "Racoon Dog",
        "Siberian Musk Deer",
        "Eurasian Eagle Owl",
        "Long-tailed Shrike",
        "Korean Salamander",
        "Yellow-throated Marten"
      ],
      clothing: [
        "Hanbok",
        "Gat",
        "Durumagi",
        "Jeogori",
        "Chima",
        "Baji",
        "Hwarot",
        "Dapho",
        "Sseugae-chima",
        "Jokduri",
        "Norigae",
        "Po",
        "Beoseon",
        "Homi Hat",
        "Hanbok Vest"
      ],
      lore: [
        "Gumiho",
        "Samjogo",
        "Dangun",
        "Haetae",
        "Bulgasari",
        "Dokkaebi",
        "Gwisin",
        "Haneulnim",
        "Mugunghwa",
        "Taegeuk",
        "Mountain Spirit",
        "Dragon King",
        "Chilseong",
        "Cheongung",
        "Jiri Spirit"
      ]
    },
  
    Japan: {
      animals: [
        "Japanese Macaque",
        "Tanuki",
        "Koi",
        "Sika Deer",
        "Iriomote Cat",
        "Japanese Serow",
        "Red-crowned Crane",
        "Japanese Giant Salamander",
        "Ryukyu Flying Fox",
        "Blakiston’s Fish Owl",
        "Snow Fox",
        "Japanese Pond Turtle",
        "Wild Boar",
        "Green Pheasant",
        "Japanese Weasel"
      ],
      clothing: [
        "Kimono",
        "Yukata",
        "Hakama",
        "Haori",
        "Obi",
        "Geta",
        "Zori",
        "Jinbei",
        "Furisode",
        "Montsuki",
        "Tabi",
        "Hanten",
        "Happi",
        "Uchikake",
        "Kanzashi"
      ],
      lore: [
        "Amaterasu",
        "Susanoo",
        "Tsukuyomi",
        "Kitsune",
        "Oni",
        "Tengu",
        "Kappa",
        "Yurei",
        "Torii",
        "Sakura",
        "Katana Spirit",
        "Namazu",
        "Shisa",
        "Tanabata Spirit",
        "Fuji Spirit"
      ]
    },
  
    Mexico: {
      animals: [
        "Jaguar",
        "Ocelot",
        "Axolotl",
        "Coati",
        "Quetzal",
        "Mexican Gray Wolf",
        "Spider Monkey",
        "Coyote",
        "Iguana",
        "Armadillo",
        "Scarlet Macaw",
        "Xoloitzcuintli",
        "Roadrunner",
        "Monarch Butterfly",
        "Rattlesnake"
      ],
      clothing: [
        "Huipil",
        "Rebozo",
        "Charro Suit",
        "Sombrero",
        "Serape",
        "Guayabera",
        "Tehuana Dress",
        "Puebla Dress",
        "Baja Hoodie",
        "Quechquémitl",
        "Huaraches",
        "Sarape Poncho",
        "Tlacoyal Hat",
        "Chiapaneca Dress",
        "Mariachi Jacket"
      ],
      lore: [
        "Quetzalcoatl",
        "Huitzilopochtli",
        "Tezcatlipoca",
        "Xolotl",
        "Coatlicue",
        "Alebrije",
        "Calavera",
        "Sun Stone",
        "Popocatépetl & Iztaccíhuatl",
        "Jaguar God",
        "Cenote Spirits",
        "La Llorona",
        "Eagle Warrior",
        "Serpent of Light",
        "Día de los Muertos Spirit"
      ]
    }
  };
  